App_Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from . import views


urlpatterns = [
    path('', views.select_lang_redirect),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += i18n_patterns(
    
    # Custom Views
    path('404', views.page_not_found_view),
    path('403', views.page_forbidden_view),
    path('500', views.page_server_error_view),

    # APP
    path('', include('ampool_auth.urls', namespace='auth')),
    path('', include('ampool_website.urls', namespace='website')),
    
    # PACKAGES
    path('change/language/', views.activate_language, name='activate_lang'),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "App_Config.views.page_not_found_view"

ampool_auth/urls.py
from django.urls import path
from . import views


app_name = 'auth'
urlpatterns = [
    path('sign-in', views.sign_in_page, name='signin'),
    path('sign-up', views.sign_up_page, name='signup'),
    path('sign-out', views.sign_out_page, name='signout'),
    path('enter-sms-code/<uidb64>/<token>', views.enter_sms_code, name='enter-sms-code'),
]

ampool_website/urls.py
from django.urls import path
from . import views


app_name = 'website'
urlpatterns = [
    path('', views.IndexPage.as_view(), name='index'),
    path('doctors', views.DoctorsPage.as_view(), name='doctors'),
    path('blogs/', views.BlogsPage.as_view(), name='blogs'),
    path('blogs/<slug:slug>', views.BlogDetailPage.as_view(), name='blog_details'),
    path('blogs/like/<slug:slug>', views.BlogLikePage.as_view(), name='blog_like'),
    path('blogs/comment/save', views.CommentSaveURL.as_view(), name='comment_save'),
    path('blogs/search/', views.SearchBoxURL.as_view(), name='blog_search'),
    path('blogs/search/tags/', views.SearchTagURL.as_view(), name='blog_search_tag'),
    path('blogs/search/categories/', views.SearchCategoryURL.as_view(), name='blog_search_category'),
    path('contact-us', views.ContactUsPage.as_view(), name='contactus'),
]

templates/website/shared/_footer.html
{% load static i18n website_tags%}

<!-- + Footer -->
<footer class="footer">
    
    <div class="img__wrapper">
        <a href="#ampool_ir">
            <img src="{% static 'img/arrow-up-circle.svg' %}" alt="www.ampool.ir">
        </a>
    </div>

    <div class="logo__wrapper">
        <img src="{% static 'img/logo.png' %}" alt="www.ampool.ir">
    </div>

    <section class="footer__wrapper">

        <div class="footer__right">
            <p>
                {% if request.LANGUAGE_CODE == 'fa' %}
                آمپول سامانه جامع سلامت و درمان کشور است. در این سامانه میتوانید از بین پزشکان عضو آمپول نوبت آنلاین بگیــرید ، پرونده الکتــرونیک و ســابقه درمانی خود را همیشه در گوشـی همــراه خود بهمـراه داشتـه باشید، مشـاوره بگیرید، اطلاعات بیمارستان ها و داروخانه ها و مراکز تصـویر برداری نزدیک خود را مشاهده کنید. این ســامانه هوشمند پس از ویزیت پزشـک نیز همراه شما بوده و با توجه به تجویز پزشک ، شما را تا اتمام پروسـه درمان شما همـــراهی می کند
                {% elif request.LANGUAGE_CODE == 'en' %}
                Ampoule is the comprehensive health and treatment system of the country. In this system, you can make appointments online among the doctors who are injections, always have your electronic file and medical history with you in your mobile phone, get advice, see the information of hospitals, pharmacies and imaging centers near you. This smart system will be with you after the doctor's visit and will accompany you until the end of your treatment process, according to the doctor's prescription.
                {% elif request.LANGUAGE_CODE == 'ar' %}
                أمبولة هو نظام شامل للصحة والعلاج في البلاد. في هذا النظام ، يمكنك تحديد مواعيد عبر الإنترنت بين الأطباء الذين يقومون بالحقن ، مع الاحتفاظ دائمًا بملفك الإلكتروني وتاريخك الطبي معك في هاتفك المحمول ، والحصول على المشورة ، والاطلاع على معلومات المستشفيات والصيدليات ومراكز التصوير القريبة منك. سيكون هذا النظام الذكي معك بعد زيارة الطبيب وسيرافقك حتى نهاية عملية العلاج ، حسب وصفة الطبيب.
                {% endif %}
            </p>
            <br>
            <ul>
                <li><a href="{% url 'website:index' %}">{% if request.LANGUAGE_CODE == 'fa' %} خانه {% elif request.LANGUAGE_CODE == 'en' %} Home {% elif request.LANGUAGE_CODE == 'ar' %} فهرس {% endif %}</a></li>
                <li><a href="{% url 'website:doctors' %}">{% if request.LANGUAGE_CODE == 'fa' %} پزشکان {% elif request.LANGUAGE_CODE == 'en' %} Doctors {% elif request.LANGUAGE_CODE == 'ar' %} الأطباء {% endif %}</a></li>
                <li><a href="{% url 'website:blogs' %}">{% if request.LANGUAGE_CODE == 'fa' %} مجله سلامت {% elif request.LANGUAGE_CODE == 'en' %} Journal of Health {% elif request.LANGUAGE_CODE == 'ar' %} مجلة الصحة {% endif %}</a></li>
                <li><a href="{% url 'website:contactus' %}">{% if request.LANGUAGE_CODE == 'fa' %} ارتباط باما {% elif request.LANGUAGE_CODE == 'en' %} ContactUs {% elif request.LANGUAGE_CODE == 'ar' %} اتصل بنا {% endif %}</a></li>
            </ul>
        </div>

        <div class="footer__left">
            
            <div class="img__wrapper">
                <a href=""><img src="{% static 'img/multi.png' %}" alt=""></a>
                <a href=""><img src="{% static 'img/multi.png' %}" alt=""></a>
                <a href=""><img src="{% static 'img/multi.png' %}" alt=""></a>
            </div>

            <div class="link__wrapper">
                <h3>{% if request.LANGUAGE_CODE == 'fa' %}شبکه های اجتماعی ما:{% elif request.LANGUAGE_CODE == 'en' %}Our social networks:{% elif request.LANGUAGE_CODE == 'ar' %}شبكاتنا الاجتماعية:{% endif %}</h3>
                <div>
                    <a href=""><img src="{% static 'img/aparat.svg' %}" alt=""></a>
                    <a href=""><img src="{% static 'img/telegram.svg' %}" alt=""></a>
                    <a href=""><img src="{% static 'img/instagram.svg' %}" alt=""></a>
                </div>
            </div>

            <div class="btns__wrapper mt-2">
                {% if request.user.is_authenticated %}
                <a href="">{% if request.LANGUAGE_CODE == 'fa' %}ورود به پنل کاربری{% elif request.LANGUAGE_CODE == 'en' %}Login to the user panel{% elif request.LANGUAGE_CODE == 'ar' %}تسجيل الدخول إلى لوحة المستخدم{% endif %}</a>
                <a href="{% url 'auth:signout' %}">{% if request.LANGUAGE_CODE == 'fa' %}خروج{% elif request.LANGUAGE_CODE == 'en' %}Exit{% elif request.LANGUAGE_CODE == 'ar' %}مخرج{% endif %}</a>
                {% else %}
                <a href="{% url 'auth:signin' %}">{% if request.LANGUAGE_CODE == 'fa' %}ورود به آمپول{% elif request.LANGUAGE_CODE == 'en' %}Enter the ampoule{% elif request.LANGUAGE_CODE == 'ar' %}أدخل الأمبولة{% endif %}</a>
                <a href="{% url 'auth:signup' %}">{% if request.LANGUAGE_CODE == 'fa' %}ثبت نام در آمپول{% elif request.LANGUAGE_CODE == 'en' %}Enrollment in ampoules{% elif request.LANGUAGE_CODE == 'ar' %}التسجيل في أمبولات{% endif %}</a>
                {% endif %}
            </div>

        </div>
        
    </section>
    <p class="whereis_it">دفتر مرکزی: تهران - خیابان ولیعصر - خیابان ناهید غربی - پلاک 48 - طبقه سوم   - واحد 304</p>

    <section class="footer__last__item">
        <p>{% if request.LANGUAGE_CODE == 'fa' %}کلیه حقوق مادی و معنوی متعلق به ampool.ir است{% elif request.LANGUAGE_CODE == 'en' %}All Material and Intellectual Rights belong to Ampool.ir{% elif request.LANGUAGE_CODE == 'ar' %}جميع الحقوق المادية والفكرية تنتمي إلى ampool.ir{% endif %}</p>
    </section>

</footer>
<!-- - Footer -->

<script>
    likeblog = (slug) => {
        $.ajax ({
            url: `/blogs/like/${slug}`,
            type: 'GET',
            enctype: 'multipart/form-data',
            success: (res) => {
                if(res.status == '200'){
                    document.getElementById('heart__icon').style.color = "#f00";
                    document.querySelector('.fa-iconheart').classList.remove('fa-heart-o');
                    document.querySelector('.fa-iconheart').classList.add('fa-heart');
                    document.getElementById('counter__likes').innerHTML = res.counter;
                }
                else if(res.status == '203'){
                    document.getElementById('heart__icon').style.color = "black";
                    document.querySelector('.fa-iconheart').classList.remove('fa-heart');
                    document.querySelector('.fa-iconheart').classList.add('fa-heart-o');
                    document.getElementById('counter__likes').innerHTML = res.counter;
                }
            },
            error: (err)=> {
                console.log(err.status);
            },
            contentType: false,
            processData: false,
        });

    }

    // for alert box
    const alert = document.getElementById('messages_box');
    setTimeout(() => {
        alert.style.display = 'none'
    }, 5000);

</script>




{% comment %}


<!--================ End Brands Area =================-->

<!-- start footer Area -->
<footer class="footer-area area-padding-top">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-sm-6 single-footer-widget">
                <h4>{% translate 'لینک های سریع' %}</h4>
                <ul>
                    <li><a target="_blank" href="http://127.0.0.1:3000/account/dashboard/">{% if request.LANGUAGE_CODE == 'fa' %}حساب کاربری{% else %}Account{% endif %}</a></li>
                    <li><a href="{% url 'website:doctors' %}">{% if request.LANGUAGE_CODE == 'fa' %}دکتر‌ها{% else %}Doctors{% endif %}</a></li>
                    <li><a href="{% url 'website:blogs' %}">{% if request.LANGUAGE_CODE == 'fa' %}بلاگ ها{% else %}Blogs{% endif %}</a></li>
                    <li><a href="{% url 'website:contactus' %}">{% if request.LANGUAGE_CODE == 'fa' %}تماس باما{% else %}contact us{% endif %}</a></li>
                </ul>
            </div>
            <div class="col-lg-6 col-sm-6 single-footer-widget">
                <h4>امکانات</h4>
                <ul>
                    <li>{% if request.LANGUAGE_CODE == 'fa' %}رزور کردن وقت{% else %}Book time{% endif %}</li>
                    <li>{% if request.LANGUAGE_CODE == 'fa' %}مشاوره گرفتن از پزشک{% else %}Get medical advice{% endif %}</li>
                    <li>{% if request.LANGUAGE_CODE == 'fa' %}مشاهده ی مدارک پزشک‌ها{% else %}View doctors' records{% endif %}</li>
                    <li>{% if request.LANGUAGE_CODE == 'fa' %}مطالعه کردن بلاگ‌ها{% else %}Reading blogs{% endif %}</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row footer-bottom d-flex justify-content-between">
        <p class="col-lg-8 col-sm-12 footer-text m-0">
            {% if request.LANGUAGE_CODE == 'fa' %}این وبسایت توسط{% else %}This website has been designed by {% endif %} <a class="text-dark font-weight-bold" href="https://www.instagram.com/saeedreza_wu/" target="_blank">{% if request.LANGUAGE_CODE == 'fa' %}سعیدرضا غضنفری{% else %}SaeedReza Ghazanfari{% endif %}</a> {% if request.LANGUAGE_CODE == 'fa' %}طراحی شده است {% else %}{% endif %} 
        </p>
    </div>
    </div>
</footer>
<!-- End footer Area -->

<script>
    likeblog = (slug) => {
        $.ajax ({
            url: `/blogs/like/${slug}`,
            type: 'GET',
            enctype: 'multipart/form-data',
            success: (res) => {
                if(res.status == '200'){
                    document.getElementById('hearticon').classList.add('text-danger');
                    document.getElementById('heartcolor').classList.add('text-danger');
                    document.getElementById('youareliked').style.display = 'inline';
                    document.getElementById('counterlikes').innerHTML = res.counter;
                }
                else if(res.status == '203'){
                    document.getElementById('hearticon').classList.remove('text-danger');
                    document.getElementById('heartcolor').classList.remove('text-danger');
                    document.getElementById('youareliked').style.display = 'none';
                    document.getElementById('counterlikes').innerHTML = res.counter;
                }
            },
            error: (err)=> {
                console.log(err.status);
            },
            contentType: false,
            processData: false,
        });

    }

    // for alert box
    const alert = document.getElementById('alertme');
    setTimeout(() => {
        alert.style.display = 'none'
    }, 5000)
</script>

{% endcomment %}

templates/website/shared/_footer_ref.html
{% load static %}

<script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
<script type="text/javascript" src="{% static 'verndors/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'verndors/owl.carousel.min.js' %}"></script>

templates/website/shared/_header.html
{% load i18n static %}

<div class="bg__loader" id="bg__loader">
    <div class="wrapper__loaging">
        <div class="loading__item"></div>
        <p>
            {% if request.LANGUAGE_CODE == 'fa' %}در حال بارگزاری آمپول...{% elif request.LANGUAGE_CODE == 'en' %}Ampool is Loading...{% elif request.LANGUAGE_CODE == 'ar' %}يتم تحميل امبول ...{% endif %}
        </p>
    </div>
</div>

<div class="bg__darkglass"></div>
<div id="ampool_ir"></div>

{% if messages %}
<div class="messages_box" id="messages_box">
    {% for msg in messages %}
    <div class="message_item msg__{% if msg.tags == 'error' %}error{% elif msg.tags == 'info' %}info{% elif msg.tags == 'success' %}success{% endif %}">
        {{ msg }}
    </div>
    {% endfor %}
</div>
{% endif %}


<!-- + Header -->
<header class="header">

    <div class="header__account">
        <a href="http://127.0.0.1:3000/">
            <div>{% if request.LANGUAGE_CODE == 'fa' %}به آمپول خوش آمدید{% elif request.LANGUAGE_CODE == 'en' %}Click for Advice{% elif request.LANGUAGE_CODE == 'ar' %}انقر للحصول على المشورة{% endif %}</div>
        </a>
    </div>

    <section class="header__navbar">

        <div class="header__navbar__logo">
            <a href="{% url 'website:index' %}">
                <img src="{% static 'img/logo-pure.png' %}" title="www.ampool.ir" alt="www.ampool.ir">
                <div>
                    <span>{% if request.LANGUAGE_CODE == 'fa' %}وبسایت آمپول{% elif request.LANGUAGE_CODE == 'en' %}Welcome to Ampool{% elif request.LANGUAGE_CODE == 'ar' %}مرحبا بكم في أمبول{% endif %}</span>
                    <span>{{ request.user.get_full_name }}</span>
                </div>
            </a>
        </div>

        <nav class="header__navbar__navitems">

            <div class="toggle__nav">
                <i class="fa fa-chevron-left"></i>
            </div>
            
            <div class="section__header">
                {% if request.user.is_authenticated %}
                {% if request.user.profile %}<img src="{{ request.user.profile.url }}" alt="{{ request.user.username }}" /> {% endif %}

                <div>
                    <p>{{ request.user.get_full_name }}</p>
                    <p><span>{% if request.LANGUAGE_CODE == 'fa' %}کدکاربری:{% elif request.LANGUAGE_CODE == 'en' %}UserName:{% elif request.LANGUAGE_CODE == 'ar' %}الرقم السري للمستخدم:{% endif %}</span> {{ request.user.username }}</p>
                </div>
                {% endif %}
            </div>

            <div class="among__gap"></div>
            
            <ul>
                <li><a href="{% url 'website:index' %}" {% if request.path == '/fa/' or request.path == '/en/' or request.path == '/ar/' %}class="active"{% endif %}><i class="fa fa-home"></i> {% if request.LANGUAGE_CODE == 'fa' %} خانه {% elif request.LANGUAGE_CODE == 'en' %} Home {% elif request.LANGUAGE_CODE == 'ar' %} فهرس {% endif %}</a></li>
                <li><a href="{% url 'website:doctors' %}" {% if request.path == '/fa/doctors' or request.path == '/en/doctors' or request.path == '/ar/doctors' %}class="active"{% endif %}><i class="fa fa-user"></i> {% if request.LANGUAGE_CODE == 'fa' %} پزشکان {% elif request.LANGUAGE_CODE == 'en' %} Doctors {% elif request.LANGUAGE_CODE == 'ar' %} الأطباء {% endif %}</a></li>
                <li><a href="{% url 'website:blogs' %}" {% if '/blogs' in request.path %}class="active"{% endif %}><i class="fa fa-newspaper-o"></i> {% if request.LANGUAGE_CODE == 'fa' %} مجله سلامت {% elif request.LANGUAGE_CODE == 'en' %} Journal of Health {% elif request.LANGUAGE_CODE == 'ar' %} مجلة الصحة {% endif %}</a></li>
                <li><a href="{% url 'website:contactus' %}" {% if request.path == '/fa/contact-us' or request.path == '/en/contact-us' or request.path == '/ar/contact-us' %}class="active"{% endif %}><i class="fa fa-phone"></i> {% if request.LANGUAGE_CODE == 'fa' %} ارتباط باما {% elif request.LANGUAGE_CODE == 'en' %} ContactUs {% elif request.LANGUAGE_CODE == 'ar' %} اتصل بنا {% endif %}</a></li>
            </ul>
        </nav>

        <div class="header__navbar__controls">
            <nav>
                {% if request.user.is_authenticated %}
                <a href="{% url 'auth:signout' %}">{% if request.LANGUAGE_CODE == 'fa' %}خروج{% elif request.LANGUAGE_CODE == 'en' %}Logout{% elif request.LANGUAGE_CODE == 'ar' %}مخرج{% endif %}</a> | 
                <a href="http://127.0.0.1:3000/">{% if request.LANGUAGE_CODE == 'fa' %}حساب کاربری{% elif request.LANGUAGE_CODE == 'en' %}Panel{% elif request.LANGUAGE_CODE == 'ar' %}لوجة{% endif %}</a> | 
                {% else %}
                <a href="{% url 'auth:signin' %}">{% if request.LANGUAGE_CODE == 'fa' %}ورود{% elif request.LANGUAGE_CODE == 'en' %}Login{% elif request.LANGUAGE_CODE == 'ar' %}تسجيل الدخول{% endif %}</a> | 
                <a href="{% url 'auth:signup' %}">{% if request.LANGUAGE_CODE == 'fa' %}ثبت نام{% elif request.LANGUAGE_CODE == 'en' %}Register{% elif request.LANGUAGE_CODE == 'ar' %}يسجل{% endif %}</a> | 
                {% endif %}
                <a id="click_lang_open_id">{{ request.LANGUAGE_CODE|upper }}</a>

                <ul id="lang_wrapper" class="d-none">
                    {% if request.LANGUAGE_CODE == 'en' %}
                    <li><a href="{% url 'activate_lang' %}?lang=fa&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">Fa</a></li>
                    <li><a href="{% url 'activate_lang' %}?lang=ar&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">Ar</a></li>
                    {% elif request.LANGUAGE_CODE == 'fa' %}
                    <li><a href="{% url 'activate_lang' %}?lang=en&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">En</a></li>
                    <li><a href="{% url 'activate_lang' %}?lang=ar&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">Ar</a></li>
                    {% elif request.LANGUAGE_CODE == 'ar' %}
                    <li><a href="{% url 'activate_lang' %}?lang=fa&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">Fa</a></li>
                    <li><a href="{% url 'activate_lang' %}?lang=en&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">En</a></li>
                    {% endif %}
                </ul>

            </nav>
            <nav>
                <img src="{% static 'img/multi.png' %}" alt="">
            </nav>
            <nav id="menubar__handler">
                <i class="fa fa-bars"></i>
            </nav>
        </div>

    </section>
        
</header>
<!-- - Header -->




























{% comment %}

{% load i18n static %}


<!--================ messages box =================-->
{% for msg in messages %}

<div class="alert alert-{% if msg.tags == 'error' %}danger{% elif msg.tags == 'info' %}info{% elif msg.tags == 'success' %}success{% elif msg.tags == 'warning' %}warning{% endif %} alert-dismissible alertme" id="alertme">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ msg }}
</div>
{% empty %}
{% endfor %}
<!--================ messages box =================-->

<!--================Header Menu Area =================-->
<header class="header_area">
    <div class="top_menu row m0">
        <div class="container">
            <div class="float-left">
                {% if request.LANGUAGE_CODE == 'en' %}
                    <a href="{% url 'activate_lang' %}?lang=fa&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">Fa</a>
                    <a href="{% url 'activate_lang' %}?lang=ar&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">Ar</a>
                {% elif request.LANGUAGE_CODE == 'fa' %}
                    <a href="{% url 'activate_lang' %}?lang=en&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">En</a>
                    <a href="{% url 'activate_lang' %}?lang=ar&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">Ar</a>
                {% elif request.LANGUAGE_CODE == 'ar' %}
                    <a href="{% url 'activate_lang' %}?lang=fa&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">Fa</a>
                    <a href="{% url 'activate_lang' %}?lang=en&url={{ request.path|slice:'4:' }}" class="dn_btn mr-3">En</a>
                {% endif %}

                {% if request.user.is_authenticated %}
                <a href="{% url 'auth:signout' %}" class="dn_btn mr-3">{% if request.LANGUAGE_CODE == 'fa' %}خروج{% elif request.LANGUAGE_CODE == 'en' %}Logout{% elif request.LANGUAGE_CODE == 'ar' %}مخرج{% endif %}</a>
                <a href="http://127.0.0.1:3000/" class="dn_btn mr-3">{% if request.LANGUAGE_CODE == 'fa' %}حساب کاربری{% elif request.LANGUAGE_CODE == 'en' %}Panel{% elif request.LANGUAGE_CODE == 'ar' %}لوجة{% endif %}</a>
                {% else %}
                <a href="{% url 'auth:signin' %}" class="dn_btn mr-3">{% if request.LANGUAGE_CODE == 'fa' %}ورود{% elif request.LANGUAGE_CODE == 'en' %}Login{% elif request.LANGUAGE_CODE == 'ar' %}تسجيل الدخول{% endif %}</a>
                <a href="{% url 'auth:signup' %}" class="dn_btn mr-3">{% if request.LANGUAGE_CODE == 'fa' %}ثبت نام{% elif request.LANGUAGE_CODE == 'en' %}Register{% elif request.LANGUAGE_CODE == 'ar' %}يسجل{% endif %}</a>
                {% endif %}

            </div>
            <div class="float-right">
                {% if request.user.is_authenticated %}
                    <p class="pt-2">{{ request.user.get_full_name }} ({{ request.user.username }}){% if request.user.profile %}<img src="{{ request.user.profile.url }}" class="mx-2" style="height: 20px; border-radius: 50%; width: 20px;" /> {% endif %}</p>
                {% else %}
                {% endif %}
            </div>
        </div>	
    </div>	
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item mx-4"><a class="nav-link {% if request.path == '/fa/' or request.path == '/en/' or request.path == '/ar/' %}text-primary{% endif %}" href="{% url 'website:index' %}">{% if request.LANGUAGE_CODE == 'fa' %} خانه {% elif request.LANGUAGE_CODE == 'en' %} Home {% elif request.LANGUAGE_CODE == 'ar' %} فهرس {% endif %}</a></li> 
                        <li class="nav-item mx-4"><a class="nav-link {% if request.path == '/fa/doctors' or request.path == '/en/doctors' or request.path == '/ar/doctors' %}text-primary{% endif %}" href="{% url 'website:doctors' %}">{% if request.LANGUAGE_CODE == 'fa' %} پزشک ها {% elif request.LANGUAGE_CODE == 'en' %} Doctors {% elif request.LANGUAGE_CODE == 'ar' %} الأطباء {% endif %}</a></li>    
                        <li class="nav-item mx-4"><a class="nav-link {% if '/blogs' in request.path %}text-primary{% endif %}" href="{% url 'website:blogs' %}">{% if request.LANGUAGE_CODE == 'fa' %} پست ها {% elif request.LANGUAGE_CODE == 'en' %} Blogs {% elif request.LANGUAGE_CODE == 'ar' %} المدونات {% endif %}</a></li>
                        <li class="nav-item mx-4"><a class="nav-link {% if request.path == '/fa/contact-us' or request.path == '/en/contact-us' or request.path == '/ar/contact-us' %}text-primary{% endif %}" href="{% url 'website:contactus' %}">{% if request.LANGUAGE_CODE == 'fa' %} ارتباط باما {% elif request.LANGUAGE_CODE == 'en' %} ContactUs {% elif request.LANGUAGE_CODE == 'ar' %} اتصل بنا {% endif %}</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</header>
<!--================Header Menu Area =================-->

{% endcomment %}