App_Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from . import views


urlpatterns = [
    path('', views.select_lang_redirect),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += i18n_patterns(
    
    # Custom Views
    path('404', views.page_not_found_view),
    path('403', views.page_forbidden_view),
    path('500', views.page_server_error_view),

    # APP
    path('', include('ampool_auth.urls', namespace='auth')),
    path('', include('ampool_website.urls', namespace='website')),
    
    # PACKAGES
    path('change/language/', views.activate_language, name='activate_lang'),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "App_Config.views.page_not_found_view"

ampool_website/urls.py
from django.urls import path
from . import views


app_name = 'website'
urlpatterns = [
    path('', views.IndexPage.as_view(), name='index'),
    path('doctors', views.DoctorsPage.as_view(), name='doctors'),
    path('blogs/', views.BlogsPage.as_view(), name='blogs'),
    path('blogs/<slug:slug>', views.BlogDetailPage.as_view(), name='blog_details'),
    path('blogs/like/<slug:slug>', views.BlogLikePage.as_view(), name='blog_like'),
    path('blogs/comment/save', views.CommentSaveURL.as_view(), name='comment_save'),
    path('blogs/search/', views.SearchBoxURL.as_view(), name='blog_search'),
    path('blogs/search/tags/', views.SearchTagURL.as_view(), name='blog_search_tag'),
    path('blogs/search/categories/', views.SearchCategoryURL.as_view(), name='blog_search_category'),
    path('contact-us', views.ContactUsPage.as_view(), name='contactus'),
]

ampool_website/models.py
import datetime
from django.db import models
from django.utils.translation import gettext_lazy as _
from ampool_auth.models import User
from ampool_jobs.models import DoctorModel
from Extentions.utils import jalali_convertor, blog_image_path, get_blog_code


class DoctorNotesModel(models.Model):
    doctor = models.ForeignKey(to=DoctorModel, on_delete=models.CASCADE, verbose_name=_('پزشک'))
    short_title = models.CharField(max_length=100, verbose_name=_('عنوان کوتاه'))
    text = models.TextField(max_length=400, verbose_name=_('متن'))
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = _('نوت پزشک')
        verbose_name_plural = _('نوت های پرشکان')

    def __str__(self):
        return self.short_title

    def get_full_name(self):
        return f'{self.doctor.user.first_name} {self.doctor.user.last_name}'
    get_full_name.short_description = _('نام پزشک')


class BlogModel(models.Model):
    slug = models.SlugField(unique=True, default=get_blog_code, verbose_name=_('مقدار در url'))
    image = models.ImageField(upload_to=blog_image_path, null=True, blank=True, verbose_name=_('تصویر'))
    writer = models.ForeignKey(to=DoctorModel, blank=True, null=True, on_delete=models.CASCADE, verbose_name=_('نویسنده'), help_text=_('آگر نویسنده ای انتخاب نشود، این پست توسط پشتیبان نوشته شده است'))
    categories = models.ManyToManyField(to='CategoryModel', verbose_name=_('دسته بندی ها'))
    tags = models.ManyToManyField(to='TagModel', verbose_name=_('تگ ها'))
    title = models.CharField(max_length=100, verbose_name=_('عنوان'))
    desc = models.TextField(verbose_name=_('متن مقاله'))
    short_desc = models.CharField(max_length=500, verbose_name=_('متن کوتاه'))
    is_published = models.BooleanField(default=False, verbose_name=_('منتشر شود؟'))
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = _('بلاگ')
        verbose_name_plural = _('بلاگ‌ها')

    def __str__(self):
        return self.title

    def j_created(self):
        return jalali_convertor(time=self.created, output='j_date')
    j_created.short_description = _('تاریخ انتشار')

    def j_month(self):
        return jalali_convertor(time=self.created, output='j_month')

    def prev_post(self):
        prev_id = int(self.id) - 1
        blog = BlogModel.objects.filter(id=prev_id, is_published=True).first()
        if blog:
            return blog
        return None

    def next_post(self):
        next_id = int(self.id) + 1
        blog = BlogModel.objects.filter(id=next_id, is_published=True).first()
        if blog:
            return blog
        return None

    def get_full_name(self):
        try:
            return f'{self.writer.user.first_name} {self.writer.user.last_name}'
        except:
            return _('پشتیبان')
    get_full_name.short_description = _('نام نویسنده')


class CommentModel(models.Model):
    reply = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('پاسخ'))
    message = models.TextField(verbose_name=_('نظر'))
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name=_('کاربر'))
    blog = models.ForeignKey(to=BlogModel, on_delete=models.CASCADE, verbose_name=_('بلاگ'))
    created = models.DateTimeField(auto_now_add=True)
    is_reply = models.BooleanField(default=False, verbose_name=_('پاسخ؟'))
    is_show = models.BooleanField(default=False, verbose_name=_('نمایش؟'))
    is_read = models.BooleanField(default=False, verbose_name=_('توسط نویسنده خوانده شده؟'))

    class Meta:
        ordering = ['-id']
        verbose_name = _('نظر کاربر')
        verbose_name_plural = _('نظرات کاربران')

    def j_created(self):
        return jalali_convertor(time=self.created, output='j_date')
    j_created.short_description = _('تاریخ نظر')

    def __str__(self):
        return str(self.id)

class CategoryModel(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('عنوان'))

    class Meta:
        ordering = ['-id']
        verbose_name = _('دسته بندی')
        verbose_name_plural = _('دسته بندی ها')

    def __str__(self):
        return self.title


class TagModel(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('عنوان'))

    class Meta:
        ordering = ['-id']
        verbose_name = _('تگ')
        verbose_name_plural = _('تگ ها')

    def __str__(self):
        return self.title


class BlogLikesModel(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name=_('کاربر'))
    blog = models.ForeignKey(to=BlogModel, on_delete=models.CASCADE, verbose_name=_('بلاگ'))
    
    class Meta:
        ordering = ['-id']
        verbose_name = _('پست و لایک')
        verbose_name_plural = _('پست ها و لایک ها')

    def __str__(self):
        return str(self.id)


class ContactUsModel(models.Model):
    message = models.TextField(verbose_name=_('متن ارتباط'))
    name = models.CharField(max_length=100, verbose_name=_('نام کاربر'))
    email = models.EmailField(max_length=100, verbose_name=_('ایمیل کاربر'))
    title = models.CharField(max_length=100, verbose_name=_('عنوان ارتباط'))
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = _('پیام مخاطب')
        verbose_name_plural = _('پیام های مخاطبان')

    def __str__(self):
        return str(self.title)

ampool_website/forms.py
from django import forms
from .models import CommentModel


class CommentForm(forms.ModelForm):
    at_blog = forms.CharField(widget=forms.HiddenInput())
    isreply = forms.CharField(widget=forms.HiddenInput())
    commentid = forms.IntegerField(widget=forms.HiddenInput())
    class Meta:
        model = CommentModel
        fields = ['message', 'at_blog', 'isreply', 'commentid']

ampool_website/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.http import JsonResponse
from ampool_setting.models import SettingModel
from ampool_jobs.models import DoctorModel, DoctorDegreeModel
from .models import BlogModel, CommentModel, BlogLikesModel, ContactUsModel
from .forms import CommentForm


# url: /
class IndexPage(generic.TemplateView):
    template_name = 'ampool_website/index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blogs = BlogModel.objects.filter(is_published=True).all()[:3]
        list_blogs = []
        for blog in blogs:
            comments = CommentModel.objects.filter(blog=blog, is_reply=False, is_show=True).count()
            replies = CommentModel.objects.filter(blog=blog, is_reply=True, is_show=True).count()

            list_blogs.append({
                'blog':blog, 
                'likes': BlogLikesModel.objects.filter(blog=blog).count(),
                'comments': comments + replies
            })
        context['doctors'] = DoctorModel.objects.filter(is_active=True).all()[:10]
        context['last_blogs'] = list_blogs
        return context


# url: /doctors
class DoctorsPage(generic.TemplateView):
    template_name = 'ampool_website/doctors_page.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.GET.get('name') or self.request.GET.get('skill'):
            context['doctors'] = []
            name = self.request.GET.get('name').lower()
            # skill = self.request.GET.get('skill').lower()
            if name:
                lookup1 = Q(user__first_name__icontains=name.split(' ')[0])
                try:
                    lookup2 = Q(user__last_name__icontains=name.split(' ')[1])
                    context['doctors'] += DoctorModel.objects.filter(lookup1, lookup2, is_active=True).all()
                except:
                    context['doctors'] += DoctorModel.objects.filter(lookup1, is_active=True).all()
            # if skill:
            #     degrees = DoctorDegreeModel.objects.filter(skill_title__title=skill).all()
            #     print(degrees)
            #     for degree in degrees:
            #         print(degree)
            #         context['doctors'] += degree.doctor

        else:
            context['doctors'] = DoctorModel.objects.filter(is_active=True).all()
        return context
    

# url: /blogs
class BlogsPage(generic.ListView):
    template_name = 'ampool_website/blogs_page.html'
    model = BlogModel
    def get_queryset(self):
        blogs = BlogModel.objects.filter(is_published=True).all()
        blogs_comments = []
        for blog in blogs:
            comments = CommentModel.objects.filter(blog=blog, is_reply=False, is_show=True).count()
            replies = CommentModel.objects.filter(blog=blog, is_reply=True, is_show=True).count()
            blogs_comments.append({
                'blog': blog,
                'num_comments': comments + replies
            })
        return blogs_comments
    paginate_by = 3


# url: /blogs/like/<slug:slug>
class BlogLikePage(LoginRequiredMixin, generic.View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            this_blog = BlogModel.objects.get(slug=kwargs['slug'])
            exist = BlogLikesModel.objects.filter(user=request.user, blog=this_blog).first()

            if not exist:
                like = BlogLikesModel.objects.create(user=request.user, blog=this_blog)
                if like:
                    likes = BlogLikesModel.objects.filter(blog=this_blog).count()
                    return JsonResponse({'counter': likes, 'status': 200}, safe=False)
            
            elif exist:
                dislike = BlogLikesModel.objects.get(user=request.user, blog=this_blog).delete()
                if dislike:
                    likes = BlogLikesModel.objects.filter(blog=this_blog).count()
                    return JsonResponse({'counter': likes, 'status': 203}, safe=False)

        return JsonResponse({'status': 404}, safe=False)


# url: /blogs/<slug:slug>
class BlogDetailPage(LoginRequiredMixin, generic.DetailView):
    model = BlogModel
    context_object_name = 'blog'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        thispost = context['object']
        context['form'] = CommentForm()                                                                            # send form
        context['comments'] = CommentModel.objects.filter(blog=thispost, is_reply=False, is_show=True)             # send comments
        context['replies'] = CommentModel.objects.filter(blog=thispost, is_reply=True, is_show=True)               # send replyes
        context['is_like'] = bool(BlogLikesModel.objects.filter(blog=thispost, user=self.request.user).first())    # like it?     
        context['comments_nums'] = context['comments'].count() + context['replies'].count()                                      # send comments numbers
        context['likes'] = BlogLikesModel.objects.filter(blog=thispost).count()                                                # send likes numbers

        return context
    template_name = 'ampool_website/blog_detail.html'


# url: /blogs/comment/save 
class CommentSaveURL(LoginRequiredMixin, generic.View):
    def post(self, request):
        msg = request.POST['message']
        blog_slug = request.POST['at_blog']
        reply = request.POST['isreply']
        comment_id = request.POST['commentid']

        if msg and blog_slug and reply == 'False' and comment_id == '':
            blog = BlogModel.objects.filter(slug=blog_slug).first()
            comment = CommentModel.objects.create(message=msg, user=request.user, blog=blog)
            if comment and blog:
                messages.success(request, _('نظر شما ثبت شد. بعد از تایید در سایت نمایش خواهد شد'))
                return redirect(f'/blogs/{blog_slug}')
            
            messages.success(request, _('مشکلی به وجود آمده است'))
            return redirect('/')

        elif msg and blog_slug and reply == 'True' and comment_id:
            blog = BlogModel.objects.filter(slug=blog_slug).first()
            comment = CommentModel.objects.get(id=comment_id)
            reply = CommentModel.objects.create(reply=comment, message=msg, user=request.user, blog=blog, is_reply=True)
            if reply and blog:
                messages.success(request, _('پاسخ شما ثبت شد. بعد از تایید در سایت نمایش خواهد شد'))
                return redirect(f'/blogs/{blog_slug}')

            messages.success(request, _('مشکلی به وجود آمده است'))
            return redirect('/')


# url: /blogs/search/
class SearchBoxURL(generic.ListView):
    template_name = 'ampool_website/blogs_page.html'
    model = BlogModel
    paginate_by = 3
    def get_queryset(self):
        request = self.request
        query = request.GET.get('query')
        lookup = Q(title__icontains=query) | Q(short_desc__icontains=query) | Q(writer__user__first_name__icontains=query)  | Q(writer__user__last_name__icontains=query) 
        blogs = BlogModel.objects.filter(lookup, is_published=True).distinct()

        blogs_comments = []
        for blog in blogs:
            counter = blog.commentmodel_set.filter(is_show=True).count()
            blogs_comments.append({'blog': blog, 'num_comments': counter})
        return blogs_comments

# url: /blogs/search/tags
class SearchTagURL(generic.ListView):
    template_name = 'ampool_website/blogs_page.html'
    model = BlogModel
    paginate_by = 3
    def get_queryset(self):
        request = self.request
        query = request.GET.get('query')
        blogs = BlogModel.objects.filter(tags__title__iexact=query, is_published=True).distinct()
        blogs_comments = []
        for blog in blogs:
            counter = blog.commentmodel_set.filter(is_show=True).count()
            blogs_comments.append({'blog': blog, 'num_comments': counter})
        return blogs_comments


# url: /blogs/search/categories

class SearchCategoryURL(generic.ListView):
    template_name = 'ampool_website/blogs_page.html'
    model = BlogModel
    def get_queryset(self):
        request = self.request
        query = request.GET.get('query')
        blogs = BlogModel.objects.filter(categories__title__iexact=query, is_published=True).distinct()
        blogs_comments = []
        for blog in blogs:
            counter = blog.commentmodel_set.filter(is_show=True).count()
            blogs_comments.append({'blog': blog, 'num_comments': counter})
        return blogs_comments
    paginate_by = 3


# url: /contact-us
class ContactUsPage(SuccessMessageMixin, generic.CreateView):
    template_name = 'ampool_website/contactus.html'
    model = ContactUsModel
    success_url = reverse_lazy('website:index')
    fields = ['message', 'name', 'email', 'title']
    success_message = _('با موفقیت پیام شما ارسال شد. سپاس از همراهی شما')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sets'] = SettingModel.objects.first()
        return context

ampool_website/templates/ampool_website/partials/blog_sidebar.html
{% load static i18n website_tags %}
{% last_categories as categories %}
{% last_posts as blogs %}

<div class="wrapper__1">
    <div class="img__wrapper">
        <img src="{% static 'img/search.svg' %}" alt="www.ampool.ir">
    </div>
    
    <form action="{% url 'website:blog_search' %}" method="GET" novalidate>
        
        <div class="wrapper__field">
            <input type="text" name="query" placeholder="{% translate 'در مقالات آمپول بگرد' %}">
            <button type="submit"><i class="fa fa-search"></i></button>
        </div>

    </form>
</div>
                    
<div class="wrapper__2">
    <h2>{% translate 'دسته بندی ها' %}</h2>

    <ul>
        {% for category in categories %}
        <li>
            <a href="{% url 'website:blog_search_category' %}?query={{ category.category_name }}">{{ category.category_name }}</a>
            <span>{{ category.num }}</span>
        </li>
        {% endfor %}
    </ul>

</div>

<div class="wrapper__3">
    <h2>{% translate 'آخرین مقالات' %}</h2>

    <div class="lastblog__items">

        {% for blog in blogs %}
        <div class="lastblog__items__item">
            <a href="/blogs/{{ blog.slug }}">
                <img src="{{ blog.image.url }}" alt="{{ blog.title }}">
                <div>
                    <h4>{{ blog.title }}</h4>
                    <p>{{ blog.j_created }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
        
    </div>
</div>









{% comment %}


{% load static i18n website_tags %}
{% last_categories as categories %}
{% last_posts as blogs %}

<div class="col-lg-4">
    <div class="blog_right_sidebar">
        <aside class="single_sidebar_widget search_widget">
            <form action="{% url 'website:blog_search' %}" method="GET">
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="query" placeholder="جستجوی کلمات کلیدی">
                        <div class="input-group-append">
                            <button class="btn" type="button"><i class="ti-search"></i></button>
                        </div>
                    </div>
                </div>
                <button class="button rounded-0 primary-bg text-white w-100" type="submit">{% translate 'جستجو' %}</button>
            </form>
        </aside>    

        <aside class="single_sidebar_widget post_category_widget">
            <h4 class="widget_title">{% translate 'دسته بندی' %}</h4>
            <ul class="list cat-list">
                {% for category in categories %}
                <li>
                    <a href="{% url 'website:blog_search_category' %}?query={{ category.category_name }}" class="d-flex">
                        <p>{{ category.category_name }}</p>
                        <p>({{ category.num }})</p>
                    </a>
                </li>
                {% empty %}{% endfor %}
            </ul>
        </aside>

        <aside class="single_sidebar_widget popular_post_widget">
            <h3 class="widget_title">{% translate 'پست های اخیر' %}</h3>

            {% for blog in blogs %}
            <div class="media post_item">
                <img src="{{ blog.image.url }}" alt="post" style="height: 80px; width: 80px;">
                <div class="media-body">
                    <a href="/blogs/{{ blog.slug }}">
                        <h3>{{ blog.title }}</h3>
                    </a>
                    <p>{{ blog.j_created }}</p>
                </div>
            </div>
            {% empty %}{% endfor %}
        </aside>

    </div>
</div>

{% endcomment %}

ampool_website/templates/ampool_website/partials/doctor_notes.html
{% load static website_tags %}
{% doctor_notes as notes %}
<section class="testimonial" style="{{ style }}">
    <div class="container">
        <div class="testi_slider owl-carousel owl-theme">
            {% for note in notes %}
            <div class="item">
                <div class="testi_item">
                    <div class="testimonial_image">
                        {% if note.doctor.user.profile %}<img src="{{ note.doctor.user.profile.url }}" style="height: 100px; width: 100px;" alt="{{ note.doctor.user.get_full_name }}">{% endif %}
                    </div>
                    <div class="testi_item_content">
                        <p>
                            “{{ note.text }}”
                        </p>
                        <h4>- دکتر {{ note.doctor.get_full_name }} -</h4>       
                    </div>
                </div>
            </div>
            {% empty %}
            {% endfor %}
        </div>
    </div>
</section>