App_Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from . import views


urlpatterns = [
    path('', views.select_lang_redirect),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += i18n_patterns(
    
    # Custom Views
    path('404', views.page_not_found_view),
    path('403', views.page_forbidden_view),
    path('500', views.page_server_error_view),

    # APP
    path('', include('ampool_auth.urls', namespace='auth')),
    path('', include('ampool_website.urls', namespace='website')),
    
    # PACKAGES
    path('change/language/', views.activate_language, name='activate_lang'),
    path('admin/', admin.site.urls),
)

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "App_Config.views.page_not_found_view"

ampool_website/urls.py
from django.urls import path
from . import views


app_name = 'website'
urlpatterns = [
    path('', views.IndexPage.as_view(), name='index'),
    path('doctors', views.DoctorsPage.as_view(), name='doctors'),
    path('blogs/', views.BlogsPage.as_view(), name='blogs'),
    path('blogs/<slug:slug>', views.BlogDetailPage.as_view(), name='blog_details'),
    path('blogs/like/<slug:slug>', views.BlogLikePage.as_view(), name='blog_like'),
    path('blogs/comment/save', views.CommentSaveURL.as_view(), name='comment_save'),
    path('blogs/search/', views.SearchBoxURL.as_view(), name='blog_search'),
    path('blogs/search/tags/', views.SearchTagURL.as_view(), name='blog_search_tag'),
    path('blogs/search/categories/', views.SearchCategoryURL.as_view(), name='blog_search_category'),
    path('contact-us', views.ContactUsPage.as_view(), name='contactus'),
]

ampool_jobs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from ampool_auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from Extentions.utils import doctor_degree_path, file_chat_path, jalali_convertor, ticket_image_path


class SupportersModel(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE, verbose_name=_('کاربر'))
    is_send_reply = models.BooleanField(default=False, verbose_name=_('اجازه‌ی ارسال پاسخ به کاربران'))
    is_create_blog = models.BooleanField(default=False, verbose_name=_('اجازه‌ی تولید پست'))
    is_active = models.BooleanField(default=False, verbose_name=_('فعال / غیرفعال'))
    
    class Meta:
        ordering = ['-user__id']
        verbose_name = _('پشتیبان')
        verbose_name_plural = _('پشتیبانان')

    def __str__(self):
        return str(self.user.get_full_name())

    def get_full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'
    get_full_name.short_description = _('نام پشتیبان')


class DoctorModel(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE, verbose_name=_('کاربر'))
    history = models.TextField(blank=True, null=True, verbose_name=_('سابقه ی پزشکی'))
    bio = models.TextField(max_length=500, blank=True, null=True, verbose_name=_('بیوگرافی'), help_text=_('این متن در زمان ارائه‌ی مقالات پزشکی شما در سایت، به کاربران نشان داده خواهد شد'))
    is_advised = models.BooleanField(default=False, verbose_name=_('اجازه برای مشاوره دادن به بیماران'), help_text=_('اگر این گزینه فعال این پزشک میتواند برنامه‌ی پزشکی تعیین کند و وقت مشاوره ارائه بدهد'))
    send_doctor_request_for_blogging = models.BooleanField(default=False, verbose_name=_('درخواست وبلاگنویسی'), help_text=_('آیا این پزشک درخواست برای بلاگنویسی داده است؟'))
    is_blogger = models.BooleanField(default=False, verbose_name=_('نویسنده است؟'), help_text=_('اجازه‌ی نوشتن مقالات'))
    is_active = models.BooleanField(default=False, verbose_name=_('فعال / غیرفعال'))

    class Meta:
        ordering = ['-user__id']
        verbose_name = _('پزشک')
        verbose_name_plural = _('پزشک ها')

    def __str__(self):
        return str(self.user.get_full_name())

    def get_full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'
    get_full_name.short_description = _('نام پزشک')


class TitleSkillModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('عنوان تخصص'))

    class Meta:
        ordering = ['-id']
        verbose_name = _('عنوان تخصص')
        verbose_name_plural = _('عناوین تخصص‌ها')

    def __str__(self):
        return self.title


class DoctorDegreeModel(models.Model):
    DATE_MONTH_TUPLE = (('1', _('فروردین')), ('2', _('اردیبهشت')), ('3', _('خرداد')), ('4', _('تیر')), ('5', _('مرداد')), ('6', _('شهریور')), ('7', _('مهر')), ('8', _('آبان')), ('9', _('آذر')), ('10', _('دی')), ('11', _('بهمن')), ('12', _('اسفند')), )
    doctor = models.ForeignKey(DoctorModel, blank=True, null=True, on_delete=models.CASCADE, verbose_name=_('پزشک'))
    score = models.PositiveIntegerField(default=0, verbose_name=_('امتیاز'))
    skill_title = models.ForeignKey(TitleSkillModel, blank=True, null=True, on_delete=models.CASCADE, verbose_name=_('عنوان تخصص/ها'))
    degree_image = models.ImageField(upload_to=doctor_degree_path, null=True, blank=True, verbose_name=_('تصویر مدرک'))
    # info of degree
    medical_system_code = models.IntegerField(blank=True, null=True, verbose_name=_('کد نظام پزشکی'))
    first_name = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('نام'))
    last_name = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('نام خانوادگی'))
    father_name = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('نام پدر'))
    birth_certificate_id = models.BigIntegerField(blank=True, null=True, verbose_name=_('شماره شناسنامه'))
    national_code = models.BigIntegerField(blank=True, null=True, verbose_name=_('کدملی'))
    issued_from = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('صادره از'))
    degree_date = models.DateField(blank=True, null=True, verbose_name=_('تاریخ صدور'))
    average = models.FloatField(blank=True, null=True, verbose_name=_('معدل'))
    average_chars = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('معدل با حروف'))
    medical_field_name = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('نام رشته'))
    is_valid = models.BooleanField(default=False, verbose_name=_('فعال / غیرفعال'), help_text=_('آیا این مدرک تایید شده است؟'))

    class Meta:
        ordering = ['-id']
        verbose_name = _('تخصص پزشک')
        verbose_name_plural = _('تخصص ‌های پزشکان')
    
    def __str__(self):  
        return f'{self.doctor.user.first_name} {self.doctor.user.last_name} ({self.skill_title})'

    def get_full_name(self):
        return f'{self.doctor.user.first_name} {self.doctor.user.last_name}'
    get_full_name.short_description = _('نام پزشک')
    


class DoctorConsultingTimeModel(models.Model):
    DAYS = (
        ('saturday', _('شنبه')),
        ('sunday', _('یک شنبه')),
        ('monday', _('دو شنبه')),
        ('tuesday', _('سه شنبه')),
        ('wednesday', _('چهار شنبه')),
        ('thursday', _('پنج شنبه')),
        ('friday', _('جمعه')),
    )
    TIMES = (
        ('6-8', '6-8'),
        ('8-10', '8-10'),
        ('10-12', '10-12'),
        ('12-14', '12-14'),
        ('14-16', '14-16'),
        ('16-18', '16-18'),
        ('18-20', '18-20'),
    )
    doctor = models.ForeignKey(DoctorModel, on_delete=models.CASCADE, verbose_name=_('پزشک'))
    skill = models.ManyToManyField(DoctorDegreeModel, verbose_name=_('تخصص‌ها'))
    day = models.CharField(max_length=15, blank=True, null=True, choices=DAYS, verbose_name=_('روز'))
    time = models.CharField(max_length=15, blank=True, null=True, choices=TIMES, verbose_name=_('زمان'))

    class Meta:
        ordering = ['-id']
        verbose_name = _('زمان مشاوره‌ی پزشک')
        verbose_name_plural = _('زمان‌های مشاوره‌ی پزشک')
    
    def __str__(self):  
        return self.doctor.user.first_name + ' ' + self.doctor.user.last_name


class DoctorReservingTimeModel(models.Model):
    doctor = models.ForeignKey(DoctorModel, on_delete=models.CASCADE, verbose_name=_('پزشک'))
    doctor_skill = models.ForeignKey(DoctorDegreeModel, on_delete=models.CASCADE, verbose_name=_('تخصص پزشک'))
    patient = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('بیمار'))
    requestedtime_day = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('روز درخواستی از سمت بیمار'))
    requestedtime_time = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('ساعت درخواستی از سمت بیمار'))
    is_doctor_see = models.BooleanField(default=False, verbose_name=_('آیا پزشک این درخواست را مشاهده کرده است؟'))
    visit_date = models.DateField(blank=True, null=True, verbose_name=_('تاریخ ملاقات با دکتر'))
    visit_timefrom = models.TimeField(blank=True, null=True, verbose_name=_('زمان ملاقات با دکتر از'))
    visit_timeto = models.TimeField(blank=True, null=True, verbose_name=_('زمان ملاقات با دکتر تا'))
    is_active = models.BooleanField(default=False, verbose_name=_('آیا این زمان رزرو شده است؟'))
    is_ended = models.BooleanField(default=False, verbose_name=_('آیا این ملاقات به اتمام رسیده است؟'))
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = _('زمان ملاقات پزشک')
        verbose_name_plural = _('زمان‌های ملاقات پزشک')
    
    def __str__(self):  
        return self.doctor.user.first_name + ' ' + self.doctor.user.last_name


class MessagePermissionModel(models.Model):
    patient = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('بیمار'))
    doctor = models.ForeignKey(DoctorModel, on_delete=models.CASCADE, verbose_name=_('پزشک'))
    skill = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('تخصص پزشک'))
    is_enabled = models.BooleanField(default=False, verbose_name=_('فعال بودن چت'))
    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = _('اجازه‌ی چت')
        verbose_name_plural = _('اجازه‌ی چت‌ها')
    
    def __str__(self):  
        return str(self.id)


class MessageModel(models.Model):
    msg_permission = models.ForeignKey(MessagePermissionModel, on_delete=models.CASCADE, verbose_name=_('اجازه‌ی چت'))
    reply = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('پاسخ'))
    sender = models.ForeignKey(User, related_name='msg_sender', on_delete=models.CASCADE, verbose_name=_('فرستنده'))
    receiver = models.ForeignKey(User, related_name='msg_receiver', on_delete=models.CASCADE, verbose_name=_('گیرنده'))
    msg = models.TextField(blank=True, null=True, verbose_name=_('متن پیام'))
    file = models.FileField(upload_to=file_chat_path, null=True, blank=True, verbose_name=_('فایل'))
    is_send = models.BooleanField(default=False, verbose_name=_('فرستاده شد؟'))
    is_seen = models.BooleanField(default=False, verbose_name=_('دیده شد؟'))
    is_reply = models.BooleanField(default=False, verbose_name=_('آیا این پیام پاسخ میباشد؟'))
    have_file = models.BooleanField(default=False, verbose_name=_('آیا این پیام شامل فایل میباشد؟'))
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['id']
        verbose_name = _('چت')
        verbose_name_plural = _('چت ها')
    
    def __str__(self):  
        return str(self.id)


class TicketModel(models.Model):
    DEPARTMENT_CHOICES = (
        ('finance', _('Finance and Administration')), 
        ('ac_activation', _('Account Activation')), 
        ('ac_upgrade', _('Upgrade Account')), 
        ('webSite_performance', _('WebSite Performance')), 

ampool_website/models.py
import datetime
from django.db import models
from django.utils.translation import gettext_lazy as _
from ampool_auth.models import User
from ampool_jobs.models import DoctorModel
from Extentions.utils import jalali_convertor, blog_image_path, get_blog_code


class DoctorNotesModel(models.Model):
    doctor = models.ForeignKey(to=DoctorModel, on_delete=models.CASCADE, verbose_name=_('پزشک'))
    short_title = models.CharField(max_length=100, verbose_name=_('عنوان کوتاه'))
    text = models.TextField(max_length=400, verbose_name=_('متن'))
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = _('نوت پزشک')
        verbose_name_plural = _('نوت های پرشکان')

    def __str__(self):
        return self.short_title

    def get_full_name(self):
        return f'{self.doctor.user.first_name} {self.doctor.user.last_name}'
    get_full_name.short_description = _('نام پزشک')


class BlogModel(models.Model):
    slug = models.SlugField(unique=True, default=get_blog_code, verbose_name=_('مقدار در url'))
    image = models.ImageField(upload_to=blog_image_path, null=True, blank=True, verbose_name=_('تصویر'))
    writer = models.ForeignKey(to=DoctorModel, blank=True, null=True, on_delete=models.CASCADE, verbose_name=_('نویسنده'), help_text=_('آگر نویسنده ای انتخاب نشود، این پست توسط پشتیبان نوشته شده است'))
    categories = models.ManyToManyField(to='CategoryModel', verbose_name=_('دسته بندی ها'))
    tags = models.ManyToManyField(to='TagModel', verbose_name=_('تگ ها'))
    title = models.CharField(max_length=100, verbose_name=_('عنوان'))
    desc = models.TextField(verbose_name=_('متن مقاله'))
    short_desc = models.CharField(max_length=500, verbose_name=_('متن کوتاه'))
    is_published = models.BooleanField(default=False, verbose_name=_('منتشر شود؟'))
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = _('بلاگ')
        verbose_name_plural = _('بلاگ‌ها')

    def __str__(self):
        return self.title

    def j_created(self):
        return jalali_convertor(time=self.created, output='j_date')
    j_created.short_description = _('تاریخ انتشار')

    def j_month(self):
        return jalali_convertor(time=self.created, output='j_month')

    def prev_post(self):
        prev_id = int(self.id) - 1
        blog = BlogModel.objects.filter(id=prev_id, is_published=True).first()
        if blog:
            return blog
        return None

    def next_post(self):
        next_id = int(self.id) + 1
        blog = BlogModel.objects.filter(id=next_id, is_published=True).first()
        if blog:
            return blog
        return None

    def get_full_name(self):
        try:
            return f'{self.writer.user.first_name} {self.writer.user.last_name}'
        except:
            return _('پشتیبان')
    get_full_name.short_description = _('نام نویسنده')


class CommentModel(models.Model):
    reply = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('پاسخ'))
    message = models.TextField(verbose_name=_('نظر'))
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name=_('کاربر'))
    blog = models.ForeignKey(to=BlogModel, on_delete=models.CASCADE, verbose_name=_('بلاگ'))
    created = models.DateTimeField(auto_now_add=True)
    is_reply = models.BooleanField(default=False, verbose_name=_('پاسخ؟'))
    is_show = models.BooleanField(default=False, verbose_name=_('نمایش؟'))
    is_read = models.BooleanField(default=False, verbose_name=_('توسط نویسنده خوانده شده؟'))

    class Meta:
        ordering = ['-id']
        verbose_name = _('نظر کاربر')
        verbose_name_plural = _('نظرات کاربران')

    def j_created(self):
        return jalali_convertor(time=self.created, output='j_date')
    j_created.short_description = _('تاریخ نظر')

    def __str__(self):
        return str(self.id)

class CategoryModel(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('عنوان'))

    class Meta:
        ordering = ['-id']
        verbose_name = _('دسته بندی')
        verbose_name_plural = _('دسته بندی ها')

    def __str__(self):
        return self.title


class TagModel(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('عنوان'))

    class Meta:
        ordering = ['-id']
        verbose_name = _('تگ')
        verbose_name_plural = _('تگ ها')

    def __str__(self):
        return self.title


class BlogLikesModel(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name=_('کاربر'))
    blog = models.ForeignKey(to=BlogModel, on_delete=models.CASCADE, verbose_name=_('بلاگ'))
    
    class Meta:
        ordering = ['-id']
        verbose_name = _('پست و لایک')
        verbose_name_plural = _('پست ها و لایک ها')

    def __str__(self):
        return str(self.id)


class ContactUsModel(models.Model):
    message = models.TextField(verbose_name=_('متن ارتباط'))
    name = models.CharField(max_length=100, verbose_name=_('نام کاربر'))
    email = models.EmailField(max_length=100, verbose_name=_('ایمیل کاربر'))
    title = models.CharField(max_length=100, verbose_name=_('عنوان ارتباط'))
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']
        verbose_name = _('پیام مخاطب')
        verbose_name_plural = _('پیام های مخاطبان')

    def __str__(self):
        return str(self.title)

ampool_website/forms.py
from django import forms
from .models import CommentModel


class CommentForm(forms.ModelForm):
    at_blog = forms.CharField(widget=forms.HiddenInput())
    isreply = forms.CharField(widget=forms.HiddenInput())
    commentid = forms.IntegerField(widget=forms.HiddenInput())
    class Meta:
        model = CommentModel
        fields = ['message', 'at_blog', 'isreply', 'commentid']

ampool_website/templates/ampool_website/blogs_page.html
{% extends 'website/shared/_main_layout.html' %}
{% load static i18n %}
{% block title %}{% translate 'آمپول | لیست مجلات' %}{% endblock %}
{% block extraCss %}
<meta name="keywords" content="">
<link rel="stylesheet" href="{% static 'css/blogs.css' %}" media="screen and (min-width: 801px)">
<link rel="stylesheet" href="{% static 'css/responsive/blogs-res.css' %}" media="screen and (max-width: 800px)">
{% endblock %}


{% block content %}

<!-- + Main -->
<main class="main">
    
    <section class="main__header">

        <div class="header__wrapper">
            <p>
                <i class="fa fa-home"></i><a href="/">{% translate 'صفحه نخست' %}</a> / 
                <a href="/blogs">{% translate 'مجله سلامت آمپول' %}</a>
            </p>
            <h1>{% translate 'مجله سلامت آمپول' %}</h1>
        </div>

    </section>

    <section class="main__body">
        
        <div class="body__wrapper">

            <nav class="body__nav">
                
                {% include 'ampool_website/partials/blog_sidebar.html' %}

            </nav>
            
            <section class="body__content">
                
                {% for blog in page_obj %}
                <div class="blog__item">
                    <a href="{% url 'website:blog_details' blog.blog.slug %}">
                        <div class="wrapper__dateblog">
                            <p>{{ blog.blog.j_created }}</p>
                        </div>
                        {% if blog.blog.image %}<img src="{{ blog.blog.image.url }}" alt="">{% endif %}
                        <div class="blog__item__content">
                            <h1>{{ blog.blog.title }}</h1>
                            <p>{{ blog.blog.short_desc }}</p>
                            <div>
                                <span><i class="fa fa-user-o"></i> {% if blog.blog.writer.get_full_name %}{{blog.blog.writer.get_full_name}}{% else %}{% translate 'وبسایت آمپول' %}{% endif %}</span>
                                <span><i class="fa fa-comment-o"></i> {% if blog.num_comments %}{{ blog.num_comments }}{% else %}0{% endif %} {% translate 'نظر' %}</span>
                            </div>
                        </div>
                    </a>
                </div>
                {% empty %}
                <p class="alert alert-info">{% translate 'مجله ای متناسب با عبارت مورد نظر شما پیدا نشد!' %}</p>
                {% endfor %}

                <ul class="paginator__items">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.previous_page_number }}">
                            <i class="fa fa-chevron-right"></i>
                        </a>
                    </li>
                    {% endif %}
                    {% for page in paginator.page_range %}
                        {% if page == page_obj.number %}
                            <li class="active">
                                <a href="?page={{ page }}">{{ page }}</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ page }}">{{ page }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.next_page_number }}">
                            <i class="fa fa-chevron-left"></i>
                        </a>
                    </li>
                    {% endif %}
        
                </ul>
      
            </section>

        </div>
    
    </section>

</main>
<!-- - Main -->

{% endblock %}

















{% comment %}

{% extends 'website/shared/_main_layout.html' %}
{% load static i18n %}
{% block title %}{% translate 'بلاگ ها' %}{% endblock %}


{% block content %}

<!--================Home Banner Area =================-->
<section class="banner_area" style="z-index: 12 !important;">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content d-md-flex justify-content-between align-items-center">
                <div class="mb-3 mb-md-0">
                    <h2>{% translate 'بلاگ ها' %}</h2>
                    <p>{% translate 'زمین سبز پشت هوای الوده است' %}</p>
                </div>
                <div class="page_link">
                    <a href="{% url 'website:blogs' %}">{% translate 'خانه / بلاگ ها' %}</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Blog Area =================-->
<section class="blog_area area-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5 mb-lg-0">
                <div class="blog_left_sidebar">

                    {% for blog in page_obj %}
                    <article class="blog_item">
                        <div class="blog_item_img">
                            {% if blog.blog.image %}<img class="card-img rounded-0" src="{{ blog.blog.image.url }}" alt="">{% endif %}
                            <a href="{% url 'website:blog_details' blog.blog.slug %}" class="blog_item_date">
                                <p>{{ blog.blog.j_created }}</p>
                            </a>
                        </div>
                        
                        <div class="blog_details">
                            <a class="d-inline-block" href="{% url 'website:blog_details' blog.blog.slug %}">
                                <h2>{{ blog.blog.title }}</h2>
                            </a>
                            <p>{{ blog.blog.short_desc }}</p>
                            <ul class="blog-info-link">
                                <li><a><i class="far fa-user"></i> {% if blog.blog.writer.get_full_name %}{{blog.blog.writer.get_full_name}}{% else %}{% translate 'وبسایت آمپول' %}{% endif %}</a></li>
                                <li><a><i class="far fa-comments"></i> {% if blog.num_comments %}{{ blog.num_comments }}{% else %}0{% endif %} نظر</a></li>
                            </ul>
                        </div>
                    </article>
                    {% empty %}
                    {% endfor %}

                    <nav class="blog-pagination justify-content-center d-flex">
                        <ul class="pagination">
                            
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                                    {% translate 'قبلی' %}
                                </a>
                            </li>
                        {% endif %}
                        {% for page in paginator.page_range %}
                            {% if page == page_obj.number %}
                                <li class="page-item active">
                                    <a href="?page={{ page }}" class="page-link">{{ page }}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a href="?page={{ page }}" class="page-link">{{ page }}</a>
                                </li>
                            {% endif %}
    
                            
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                                    {% translate 'بعدی' %}
                                </a>
                            </li>
                        {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
            
            <!--================ side bar =================-->
            {% include 'ampool_website/partials/blog_sidebar.html' %}

        </div>
    </div>
</section>
<!--================Blog Area =================-->

{% endblock %}
{% endcomment %}